name: johncagetribute CD

defaults:
  run:
    working-directory: /

# Runs on these events:
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - uses: appleboy/ssh-action@v0.1.2
        with:
          host: johncagetribute.org
          username: dummyUsername
          password: dummyPassword

          script: |
            cd /var/www/johncagetribute

            pm2 stop 0
        
            rm -rf JohnCageV3
            git clone https://github.com/RickLeinecker/JohnCageV3.git
            cd JohnCageV3

            cd MERN
            npm install

            cd frontend
            npm install
            npm run build
            
            pm2 start 0
         
            pm2 save

